"""user password_hash field and methods

Revision ID: 129945a6e19c
Revises: 75baa8ebe7d1
Create Date: 2024-01-22 14:45:37.153150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129945a6e19c'
down_revision = '75baa8ebe7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
